### ISSUE TITLE
Cordova User Question

### ISSUE THREAD

**Issue by hsmith825** [lrettig/react-native-stripe-new#6]
Hi Irettig,

I am interested in trying the react-native solution. I looked over the documentation and I have two questions.  I will use it in my IOS App in place of a Cordova Apple Pay plugin.
1. I am assuming I will not need to learn React ?
2.I am not certain what the Library Group refers to in "Drag StripeNative.xcodeproj into your Libraries group ". Are you referring to the Directory of Frameworks in Xcode?

Thanks!
Howard

**Comment by hsmith825** [comment]
Add
I am installing using your steps
I successfully installed cocoa pods with sudo gem install cocoa pods
npm i react-native-stripe --save fails with the following error messages
Error: EACCES, mkdir '/Users/howardsmith/.npm/type-is/1.6.11'
npm ERR!  { [Error: EACCES, mkdir '/Users/howardsmith/.npm/type-is/1.6.11']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/howardsmith/.npm/type-is/1.6.11',
npm ERR!   parent: 'connect' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.2.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "react-native-stripe" "--save"
npm ERR! cwd /Users/howardsmith
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path /Users/howardsmith/.npm/type-is/1.6.11
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/Users/howardsmith/.npm/type-is/1.6.11'
npm ERR! not ok code 0
I ran 3 times as system/administrator and always had the same results.
Any suggestions?
Thanks!
Howard

**Comment by lrettig** [comment]
Hi Howard

Thanks for checking out this module. First things first, it was written for react native, so I highly doubt it will work out of the box with cordova. You might want to try this cordova plugin instead:

http://plugins.telerik.com/cordova/plugin/stripe
(docs: https://github.com/Telerik-Verified-Plugins/Stripe/blob/master/doc/index.md)

For the record, you're probably getting this error because you need to run `npm` with sudo, i.e., `sudo npm`.

Lane
